{{- if and .Values.tlsAcme.enabled (not .Values.tlsAcme.webServer.existing) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swim-meet-order-of-finish-generator.acmeServiceName" . }}
  labels:
    {{- include "swim-meet-order-of-finish-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tlsAcme.service.type }}
  ports:
    - name: http
      port: {{ .Values.tlsAcme.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "swim-meet-order-of-finish-generator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: acme-webroot
{{- end }}
