{{- if and .Values.tlsAcme.enabled (not .Values.tlsAcme.webServer.existing) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "swim-meet-order-of-finish-generator.acmeClaimName" . }}
  labels:
    {{- include "swim-meet-order-of-finish-generator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.tlsAcme.webServer.accessMode }}
  resources:
    requests:
      storage: {{ .Values.tlsAcme.webServer.storageSize }}
  {{- if .Values.tlsAcme.webServer.storageClassName }}
  storageClassName: {{ .Values.tlsAcme.webServer.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}
