{{- if and .Values.tlsAcme.enabled .Values.tlsAcme.cert.createPlaceholder -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.tlsAcme.cert.secretName }}
  labels:
    {{- include "swim-meet-order-of-finish-generator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ include "swim-meet-order-of-finish-generator.gen-certs" . | indent 2 }}
{{- end }}
